aws_region      = "eu-west-2"
project         = "serverless-power-tuning"
table_name      = "LambdaPowerTuningTable"
lambda_zip_path = "../../lambda/package.zip"
power_tuner_arn = "arn:aws:states:eu-west-2:211125489043:stateMachine:aws-lambda-power-tuning"
